import ai from "./aisetup.js";
import { z } from "zod";
import puppeteer from "puppeteer";

const interviewReportSchema = z.object({
  matchScore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      "Overall compatibility score between the candidate and the job description.",
    ),
  title: z
    .string()
    .describe("The title for the job which the interview report is generated."),
  technicalQuestions: z
    .array(
      z.object({
        question: z.string().describe("A technical interview question."),

        answer: z
          .string()
          .describe(
            "An ideal answer explaining the concept, important points, and best practices.",
          ),

        intention: z
          .string()
          .describe(
            "Why the interviewer asks this question and what they want to evaluate.",
          ),
      }),
    )
    .describe("List of technical interview questions."),

  behaviouralQuestions: z
    .array(
      z.object({
        question: z.string().describe("A behavioral interview question."),

        answer: z
          .string()
          .describe("An ideal STAR-based answer with practical examples."),

        intention: z
          .string()
          .describe(
            "The competency or behavior the interviewer is evaluating.",
          ),
      }),
    )
    .describe("List of behavioral interview questions."),

  skillGap: z
    .array(
      z.object({
        skill: z.string().describe("A missing or weak skill."),

        severity: z
          .enum(["low", "medium", "high"])
          .describe("Importance of improving this skill."),
      }),
    )
    .describe("Skills the candidate should improve."),

  preparationPlan: z
    .array(
      z.object({
        day: z.number().describe("Day number of the preparation schedule."),

        focus: z.string().describe("Main learning objective for the day."),

        task: z
          .array(z.string().describe("A topic to study."))
          .describe("Tasks to cover during the day."),
      }),
    )
    .describe("A day-by-day interview preparation plan."),
});

export async function generateInterviewReport({
  resume,
  jobDescription,
  selfDescription,
}) {
  const prompt = `Generate an interview report based on the following resume and job description. 
    Resume: ${resume}
    Job Description: ${jobDescription}
    Self Description: ${selfDescription}`;
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseJsonSchema: z.toJSONSchema(interviewReportSchema),
    },
  });
  const report = interviewReportSchema.parse(JSON.parse(response.text));

  return report;
}

export async function generatePdfFromContent(htmlContent) {
  const browser = await puppeteer.launch({
    headless: true,
  });

  try {
    const page = await browser.newPage();

    await page.setViewport({
      width: 1240,
      height: 1754,
      deviceScaleFactor: 2,
    });

    await page.setContent(htmlContent, {
      waitUntil: "networkidle0",
    });

    await page.emulateMediaType("screen");

    await page.evaluate(async () => {
      await document.fonts.ready;
    });

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      preferCSSPageSize: true,
      displayHeaderFooter: false,
      margin: {
        top: "12mm",
        bottom: "12mm",
        left: "12mm",
        right: "12mm",
      },
    });

    return pdf;
  } finally {
    await browser.close();
  }
}

export async function generateResume({
  resume,
  jobDescription,
  selfDescription,  
}) {
  const resumePdfSchema = z.object({
    html: z
      .string()
      .describe(
        "The HTML content of the resume which can be converted to PDF using any library like puppeteer",
      ),
  });

  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
 `;
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseJsonSchema: z.toJSONSchema(resumePdfSchema),
    },
  });
  const jsonContent = JSON.parse(response.text);
  const html = await generatePdfFromContent(jsonContent.html);
  return html;
}
